### ISSUE TITLE
Cannot find module 'remix-plugin'

### ISSUE THREAD

**Issue by ryu9827** [ethereum/remix-plugin#90]
Hi there,
I'm just playing with Remix(online [new look](http://remix.ethereum.org/#optimize=false&version=soljson-v0.5.1+commit.c8a2cb62.js&appVersion=0.8.0)) and trying to develop a plugin for it.I follow the instruction in `readme.md`, but got the error `Cannot find module 'remix-plugin'`. Probably this is a very rocky mistake? but I've been stuck here for days and really need some help from here. The following is what command I ran:
```
npm install remix-plugin
```
And here is what my `index.js` looks like:
```javascript
"use babel";
import { createIframeClient } from "remix-plugin";
import http from "http";
const server = http
  .createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "text/plain" });
    res.end('Hello, world');
  })
  .listen(8000, "127.0.0.1");
console.log("Server running at port:8000");
```
Enveroment: Macbook pro
Nodejs: v 11.0
The whole error message:
```
Successfully compiled 1 file with Babel.
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'remix-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Bruce/work/Blockchain-JS/solidity-docstrings/build/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solidity-docstrings@1.0.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solidity-docstrings@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bruce/.npm/_logs/2019-06-05T23_18_13_795Z-debug.log
```
Thanks for the help in advance!

**Comment by GrandSchtroumpf** [comment]
Sorry for the delay, I missed this thread... Is this still an issue ?
I think it has been solved by https://github.com/ethereum/remix-plugin/pull/91

**Comment by GrandSchtroumpf** [comment]
Closing as it should have been solved with https://github.com/ethereum/remix-plugin/pull/91.
Will reopen if problem remains.
